application: email-report-receiver
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- node_modules/
- src/
- archive/
- e2e/
- tslint.json
- tsconfig.json

handlers:
- url: /_ah/mail/.+
  script: server.email.mail
  login: admin

- url: /oauth2callback
  script: server.main.authCallBack

- url: /home
  static_files: dist/index.html
  upload: index

- url: /api/.*
  script: server.main.app
  secure: always

- url: /static
  static_dir: dist

- url: /home
  static_files: dist/index.html
  upload: index


libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest


